### ISSUE TITLE
pytesseract may not be in path or may be available

### ISSUE THREAD

**Issue by KennBe** [sininen-blue/logic-gate-tesseract#33]

**Comment by sininen-blue** [comment]
I'll edit the python file to have an optional flag -a --absolute-path that points to a tesseract install

- this needs a settings page
- a way to select the tesseract install location
- a way to make sure that it'll use it in level creation, and
- an error in the custom level creation system

**Comment by sininen-blue** [comment]
d73d6b5c66ab99e1346a908825f389caf13882d2

everything but the custom level error, moved to #38
