### ISSUE TITLE
back after creation of level has levels from other stages

### ISSUE THREAD

**Issue by KennBe** [sininen-blue/logic-gate-tesseract#34]
![image](https://github.com/user-attachments/assets/790cc1c7-d34e-41ef-beed-478a8acb8773)

**Comment by sininen-blue** [comment]
should do a full rethink of the stage selct system

**Comment by sininen-blue** [comment]
found out that this is beacuse of the default "current_stage" value in DataManager

removed the default value and should set it somewhere in either create custom level back button, or just in the ready function of the custom level stage since no other stage works in the same way

**Comment by sininen-blue** [comment]
fixed it
