### ISSUE TITLE
should remove this, stage select.gd (or comment it out until user saves are a thing)

### ISSUE THREAD

**Issue by KennBe** [sininen-blue/logic-gate-tesseract#35]
![image](https://github.com/user-attachments/assets/08ce5cec-71e7-4811-8f58-4f65169ab756)

thos doesnt work with the user folder custom stage

**Comment by sininen-blue** [comment]
will generally redo the entire stage select system

**Comment by sininen-blue** [comment]
will try to do local saves

**Comment by sininen-blue** [comment]
need to add a system to count to number of completed levels, and max number

and also a way to auto unlock all levels

probably just have a cheat mode

**Comment by sininen-blue** [comment]
ᕕ( ᐛ )ᕗ done #50
